apiVersion: v1
kind: Secret
metadata:
  name: backend-configuration
  namespace: money-tracker
data:
  config: ewogICJzcHJpbmciOiB7CiAgICAiZGF0YXNvdXJjZSI6IHsKICAgICAgInVybCI6ICJqZGJjOnBvc3RncmVzcWw6Ly9tb25leS10cmFja2VyLWRhdGFiYXNlOjU0MzIvbW9uZXktdHJhY2tlciIsCiAgICAgICJ1c2VybmFtZSI6ICJtb25leXRyYWNrZXIiLAogICAgICAicGFzc3dvcmQiOiAibW9uZXl0cmFja2VyIiwKICAgICAgImRyaXZlci1jbGFzcy1uYW1lIjogIm9yZy5wb3N0Z3Jlc3FsLkRyaXZlciIKICAgIH0sCiAgICAicmVzb3VyY2VzIjogewogICAgICAic3RhdGljLWxvY2F0aW9ucyI6ICJjbGFzc3BhdGg6L3BhZ2VzLyIKICAgIH0sCiAgICAibXZjIjogewogICAgICAidmlldyI6IHsKICAgICAgICAic3VmZml4IjogIi5qc3AiCiAgICAgIH0KICAgIH0sCiAgICAiZGF0YSI6IHsKICAgICAgImVsYXN0aWNzZWFyY2giOiB7CiAgICAgICAgImNsdXN0ZXItbm9kZXMiOiAibW9uZXktdHJhY2tlci1pbmRleC1zZXJ2ZXI6OTMwMCIKICAgICAgfQogICAgfQogIH0KfQo=
