apiVersion: v1
kind: Service
metadata:
  name: money-tracker-database
  namespace: money-tracker
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      nodePort: 31001
  selector:
    app: money-tracker-database
