apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: money-tracker-database
  namespace: money-tracker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: money-tracker-database
    spec:
      containers:
      - name: postgres
        image: postgres
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: POSTGRES_DB
          value: 'money-tracker'
      volumes:
      - name: postgres-storage
        emptyDir: {}
